ummeli/livechat/urls.py
from django.conf.urls.defaults import patterns, url
from ummeli.livechat import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.show, name='show'),
)

ummeli/vlive/inbox/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from ummeli.vlive.inbox import views


urlpatterns = patterns('',
    url(r'^$', views.inbox, name='my_inbox'),
    url(r'^microtasks/$',
        login_required(views.MyTaskCheckoutListView.as_view()),
        name='my_microtasks'),
    )

ummeli/vlive/profile/urls.py
from django.conf.urls.defaults import patterns, url, include
from ummeli.vlive.forms import SkillWizardForm, SkillWizardFormPick
from ummeli.vlive.profile import views
from ummeli.vlive.utils import pin_required
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.conf import settings


urlpatterns = patterns('',
    url(r'^$', views.profile, name='profile'),
    url(r'^(?P<user_id>\d+)/$', views.profile_view, name='profile_view'),
    url(r'^connections/$', views.my_connections, name='my_connections'),
    url(r'^connections/(?P<user_id>\d+)/$', views.connections, name='connections'),
    url(r'^connections/add/(?P<user_id>\d+)/$', views.add_connection, name='add_connection'),
    url(r'^connections/requests/$', views.connection_requests, name='connection_requests'),
    url(r'^connections/confirm/(?P<user_id>\d+)/$', views.confirm_request, name='confirm_request'),
    url(r'^connections/reject/(?P<user_id>\d+)/$', views.reject_request, name='reject_request'),

    url(r'^connections/add_by_industry/$',
        views.add_connection_by_industry,
        name='add_connection_by_industry'),
    url(r'^connections/add_by_industry/(?P<industry>\d+)/(?P<province>\d+)/$',
        views.add_connection_by_industry_result,
        name='add_connection_by_industry_result'),
    url(r'^connections/add_by_industry/(?P<industry>\d+)/(?P<province>\d+)/page/(?P<page>\d+)/$',
        views.add_connection_by_industry_result,
        name='add_connection_by_industry_result'),

    url(r'^connections/add_by_first_name/$',
        views.add_connection_by_first_name,
        name='add_connection_by_first_name'),
    url(r'^connections/add_by_first_name/(?P<province>\d+)/$',
        views.add_connection_by_first_name_result,
        name='add_connection_by_first_name_result'),
    url(r'^connections/add_by_first_name/(?P<province>\d+)/page/(?P<page>\d+)/$',
        views.add_connection_by_first_name_result,
        name='add_connection_by_first_name_result'),

    url(r'^connections/add_by_surname/$',
        views.add_connection_by_surname,
        name='add_connection_by_surname'),
    url(r'^connections/add_by_surname/(?P<province>\d+)/$',
        views.add_connection_by_surname_result,
        name='add_connection_by_surname_result'),
    url(r'^connections/add_by_surname/(?P<province>\d+)/page/(?P<page>\d+)/$',
        views.add_connection_by_surname_result,
        name='add_connection_by_surname_result'),

    url(r'connections/(?P<user_id>\d+)/jobs/$',
        pin_required(login_required(views.ConnectionJobsListView.as_view())),
        name='connection_jobs'),
    url(r'connections/(?P<user_id>\d+)/jobs/(?P<pk>\d+)/$',
        pin_required(login_required(views.ConnectionJobsDetailView.as_view())),
        name='connection_jobs'),

    url(r'^personal/$',
        pin_required(login_required(views.PersonalDetailsEditView.as_view())),
        name='edit_personal'),
    url(r'^contact/$',
        pin_required(login_required(views.ContactDetailsEditView.as_view())),
        name='edit_contact'),
    url(r'^about_me/$',
        pin_required(login_required(views.PersonalStatementEditView.as_view())),
        name='edit_about_me'),
    url(r'^education/$', views.education_details, name='edit_education'),

    url(r'certificates/$',
        views.CertificateListView.as_view(),
        name='certificate_list'),
    url(r'certificates/(?P<pk>\d+)/$',
        pin_required(login_required(views.CertificateEditView.as_view())),
        name='certificate_edit'),
    url(r'certificates/new/$',
        pin_required(login_required(views.CertificateCreateView.as_view())),
        name='certificate_new'),
    url(r'certificates/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.CertificateDeleteView.as_view())),
        name='certificate_delete'),

    url(r'work_experiences/$',
        pin_required(login_required(views.WorkExperienceListView.as_view())),
        name='work_experience_list'),
    url(r'work_experiences/(?P<pk>\d+)/$',
        pin_required(login_required(views.WorkExperienceEditView.as_view())),
        name='workExperience_edit'),
    url(r'work_experiences/new/$',
        pin_required(login_required(views.WorkExperienceCreateView.as_view())),
        name='workExperience_new'),
    url(r'work_experiences/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.WorkExperienceDeleteView.as_view())),
        name='workExperience_delete'),

    url(r'languages/$',
        pin_required(login_required(views.LanguageListView.as_view())),
        name='language_list'),
    url(r'languages/(?P<pk>\d+)/$',
        pin_required(login_required(views.LanguageEditView.as_view())),
        name='language_edit'),
    url(r'languages/new/$',
        pin_required(login_required(views.LanguageCreateView.as_view())),
        name='language_new'),
    url(r'languages/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.LanguageDeleteView.as_view())),
        name='language_delete'),

    url(r'references/$',
        pin_required(login_required(views.ReferenceListView.as_view())),
        name='reference_list'),
    url(r'references/(?P<pk>\d+)/$',
        pin_required(login_required(views.ReferenceEditView.as_view())),
        name='reference_edit'),
    url(r'references/new/$',
        pin_required(login_required(views.ReferenceCreateView.as_view())),
        name='reference_new'),
    url(r'references/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.ReferenceDeleteView.as_view())),
        name='reference_delete'),

    url(r'community/$',
        login_required(views.MyCommunityListView.as_view()),
        name='my_community'),
    url(r'community/opportunities/$',
        login_required(views.MyOpportunitiesListView.as_view()),
        name='my_community_opportunities'),
    url(r'community/opportunities/(?P<slug>[\w-]+)/$',
        views.my_opportunity_edit,
        name='my_community_opportunities'),

    url(r'jobs/$',
        login_required(views.MyJobsListView.as_view()),
        name='my_jobs'),
    url(r'jobs/(?P<slug>[\w-]+)/$', views.my_jobs_edit, name='my_jobs'),
    url(r'jobs/delete/(?P<slug>[\w-]+)/$',
        pin_required(login_required(views.MyJobsDeleteView.as_view())),
        name='my_jobs_delete'),

    url(r'mywork/$',
        pin_required(login_required(views.SkillListView.as_view())),
        name='skills'),
    url(r'mywork/(?P<pk>\d+)/$',
        pin_required(login_required(views.SkillsEditView.as_view())),
        name='skills'),
    url(r'mywork/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.SkillDeleteView.as_view())),
        name='skills_delete'),

    url(r'mywork/new/$',views.add_skill,
        name='skills_new'),
    url(r'mywork/new/(?P<skill_id>\d+)/$',views.add_skill_from_list,
        name='skills_new'),
    url(r'mywork/primary/(?P<skill_id>\d+)/$',views.mark_skill_as_primary,
        name='skills_primary')
)

ummeli/vlive/urls.py
from django.conf.urls.defaults import patterns, url, include
from ummeli.vlive import views
from ummeli.vlive.utils import pin_required
from django.contrib.auth.decorators import login_required
from django.conf import settings

import object_tools
object_tools.autodiscover()

urlpatterns = patterns('',
    #url(r'^$', views.login, {'template_name': 'pml/login.xml'},  name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.index, name='home'),
    url(r'^my/$', views.my_ummeli, name='my_ummeli'),
    url(r'^my/settings/$', views.my_settings, name='my_settings'),
    url(r'^my/settings/password_change/$', views.password_change_view,
        name='password_change'),
    url(r'^my/settings/contact_privacy/$',
        pin_required(login_required(views.MyContactPrivacyEditView.as_view())),
        name='my_contact_privacy'),
    url(r'^my/settings/comment_settings/$',
        pin_required(login_required(views.MyCommentSettingsEditView.as_view())),
        name='my_comment_settings'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^forgot/$', views.forgot_password_view, name='forgot'),
    url(r'^tips/$', views.tips, name='tips'),
    url(r'^contactsupport/$', views.contact_support, name='contactsupport'),

    #Ummeli 2.0
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^article/', include('jmboarticles.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^ummeli/comments/', include('jmbocomments.urls')),
    url(r'^yourwords/', include('jmboyourwords.urls')),
    url(r'^poll/', include('jmboarticles.poll.urls')),
    url(r'^my/profile/', include('ummeli.vlive.profile.urls')),
    url(r'^my/inbox/', include('ummeli.vlive.inbox.urls')),
    url(r'^downloads/', include('downloads.urls')),
    url(r'^jmbo/', include('jmbo.urls')),
    url(r'^opportunities/', include('ummeli.opportunities.urls')),
    url(r'^community/', include('ummeli.vlive.community.urls')),
    url(r'^livechat/', include('livechat.urls', namespace='livechat')),
    url(r'^jmbo-analytics/', include('jmbo_analytics.urls')),
    url(r'^reporting/', include('reporting.urls')),

    url(r'^send/$', views.send, name='send'),
    url(r'^send/thanks/$', views.send_thanks, name='send_thanks'),

    #Jmbo
    url(r'^jmbo/', include('jmbo.urls')),
    url(r'^simple-autocomplete/', include('simple_autocomplete.urls')),
    #override atlas.select-location
    url(r'^select-location/$',
        'ummeli.opportunities.views.select_location',
        name='select-location',
    ),
    url(r'^', include('atlas.urls')),
    url(r'^object-tools/', include(object_tools.tools.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    )

ummeli/livechat/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.contenttypes.models import ContentType
from django.contrib import comments

Comment = comments.get_model()

class SiteManager(models.Manager):

    def get_query_set(self, *args, **kwargs):
        qs = super(SiteManager, self).get_query_set(*args, **kwargs)
        return qs.filter(sites=Site.objects.get_current(), published=True)

class LiveChat(models.Model):
    article = models.ForeignKey('jmboarticles.Article', null=True, blank=True)
    published = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    sites = models.ManyToManyField(Site)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    site = SiteManager()

    class Meta:
        ordering = ['-published', '-created_at']

    def comment_set(self):
        ct = ContentType.objects.get_for_model(self.__class__)
        return Comment.objects.filter(content_type=ct, object_pk=self.pk).order_by('-submit_date')

    def __unicode__(self):
        return 'Live Chat %s' % (self.title,)

class LiveChatResponse(models.Model):
    livechat = models.ForeignKey(LiveChat)
    author = models.ForeignKey('auth.User')
    comment = models.ForeignKey(Comment)
    response = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __unicode__(self):
        return "Live Chat Response from %s: %s" % (self.author,
            self.response[:50])

ummeli/vlive/community/forms.py
from django import forms
from ummeli.opportunities.models import *
from ummeli.vlive.forms import PMLModelForm, PMLForm


class StatusUpdateForm(PMLForm):
    title = forms.CharField(label='Status', required=True, max_length=160)


class JobEditForm(PMLModelForm):
    province = forms.ModelChoiceField(empty_label=None, queryset=Province.objects.all(), label='Province', required=True)
    category = forms.IntegerField(widget=forms.Select(choices=CATEGORY_CHOICES),
                                  required=True,
                                  min_value=1,
                                  error_messages={'min_value': 'Please choose a category.'})
    title = forms.CharField(label='title', required=True)
    description = forms.CharField(label='Description',
                                  required=True,
                                  help_text='Please provide as much information about the job as possible including contact details.',
                                  widget=forms.Textarea)

    class Meta:
        model = Job
        fields = ('province', 'category', 'title', 'description')


class OpportunityEditForm(PMLForm):
    BURSARY = 1
    TRAINING = 2
    VOLUNTEERING = 3
    INTERNSHIP = 4
    OPPORTUNITY_CHOICES = [(0, 'Please choose'),
                           (BURSARY, 'Bursary'),
                           (TRAINING, 'Training'),
                           (VOLUNTEERING, 'Volunteering'),
                           (INTERNSHIP, 'Internship')]

    opportunity_type = forms.IntegerField(widget=forms.Select(choices=OPPORTUNITY_CHOICES),
                                          required=True,
                                          min_value=1,
                                          error_messages={'min_value': 'Please choose an opportunity type.'})
    province = forms.ChoiceField(choices=[(p.pk, p.get_province_display()) for p in Province.objects.all()], label='Province', required=True)
    title = forms.CharField(label='title', required=True)
    description = forms.CharField(label='Description',
                                  required=True,
                                  help_text='Please provide as much information about the opportunity as possible including contact details.',
                                  widget=forms.Textarea)

    def get_model(self):
        if self.is_valid():
            opportunity_type = self.cleaned_data['opportunity_type']

            if opportunity_type == self.BURSARY:
                return Bursary

            if opportunity_type == self.TRAINING:
                return Training

            if opportunity_type == self.VOLUNTEERING:
                return Volunteer

            if opportunity_type == self.INTERNSHIP:
                return Internship
        return None

ummeli/vlive/profile/forms.py
from django.forms import *
from ummeli.vlive.forms import PMLForm


class IndustrySearchForm(PMLForm):
    industry = IntegerField(required=True)
    province = IntegerField(required=True)


class ConnectionNameSearchForm(PMLForm):
    name = CharField(required=True)
    province = IntegerField(required=True)

ummeli/livechat/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.sites.models import Site
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse

from ummeli.livechat.models import LiveChat

current_site = Site.objects.get_current()


def index(request):
    paginator = Paginator(LiveChat.site.all(), per_page=8)
    page = paginator.page(request.GET.get('p', 1))
    return render(request, 'livechat/index.html', {
        'paginator': paginator,
        'page': page,
    })


def show(request, pk):
    livechat = get_object_or_404(LiveChat, pk=pk, sites=current_site)
    return render(request, 'livechat/show.html', {
        'livechat': livechat,
        'current_url': reverse('livechat:show', kwargs={
            'pk': livechat.pk,
        })
    })

ummeli/vlive/inbox/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from ummeli.opportunities.models import TaskCheckout


@login_required
def inbox(request):
    context = {
        'tasks_out': TaskCheckout.objects.filter(user=request.user,
                                                state=0),
        'tasks_expired': TaskCheckout.objects.filter(user=request.user,
                                                state=2),
        }
    return render(request, 'inbox/index.html', context)


class MyTaskCheckoutListView(ListView):
    paginate_by = 10
    template_name = 'inbox/my_microtasks.html'

    def get_queryset(self):
        return TaskCheckout.objects.filter(user=self.request.user)\
                                    .order_by('state')

ummeli/vlive/templates/html/livechat/embed.html
{% load comments %}
{% load livechat_tags %}

{% get_livechat_page livechat "page" %}



{% if livechat.active %}

<div class="comments" id="comment_form">
<h2 class="comment_list" id="comment_list">{{livechat.title}}</h2>
<div class="wrap">
<p>
    {{livechat.description|safe}}
</p>
</div>
        {% if user.is_authenticated %}

            {% get_comment_form for livechat as form %}

            <form action="{% comment_form_target %}" method="post">
                {% csrf_token %}
                <div style="display:none;">
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    {{ form.timestamp }}
                    {{ form.security_hash }}
                    {{ form.honeypot }}
                    <input type="hidden" name="next" value="{{ current_url }}?&amp;answered={{answered}}&amp;popular={{popular}}" />
                </div>

                <p>
                    Write your comment:
                    <br/>Name:
                    <strong>
                        {% if user.get_profile.comment_as_anon %}
                            Anon.
                        {% else %}
                            {% if user.get_profile.fullname %}
                                {{ user.get_profile.fullname }}</a>
                            {% else %}
                                Anon.
                            {% endif %}
                        {% endif %}
                    </strong>
                    <br/>
                    <a href="{% url my_comment_settings %}">Change your comment name
                    </a><br/>
                    <div class="form-fields">
                    {{ form.comment }}
                    </div>
                </p>
                <p>
                    <input type="submit" class="btn" name="post" value="Comment" />
                </p>
            </form>

        {% else %}
            <p><a href="{% url login %}?next={{request.path}}">Sign in</a> or <a href="{% url register %}?next={{request.path}}">register</a> to chat.</p>
        {% endif %}
    </div>

{% endif %}

<div class="comment-rules">
    <div><strong>Help keep your Ummeli clean:
        <span class="tag report"><a href="#">Report</a></span>
        any comments that are abusive, inappropriate, chat or
        break any of our other commenting rules.
        </strong>
    </div>
    <div>3 separate reports and the comment will be removed.</div>
    <div><strong>Don't know the rules?</strong> <a href="/rules/">Read them here.</a></div>
</div>



{% if user.is_authenticated %}
{% get_mylivechat livechat %}
<h2 id="comment_list">My Questions</h2>
<div class="comment_list">
{% for comment in my_comments %}
    <div class="comment {% cycle 'even' 'odd' %}">
    <div class="head">
            <span class="subtext">{{ comment.submit_date|timesince }} ago</span>
        <div>{% spaceless %}
        {% if comment.is_community_moderated %}
            <strong>Moderated:</strong> {{ comment.community_moderation_flags.latest.reason }}
        {% else %}
            {% if comment.is_moderated %}
                <strong>Moderated:</strong> {{ comment.moderation_flags.latest.reason }}
            {% else %}
                {{ comment.comment }}
            {% endif %}
        {% endif %}{% endspaceless %}
        </div>
    </div>
    <div class="base">
        <span class="likes">
            {{ comment.like_count }} Like{{ comment.like_count|pluralize }}
        </span>
    </div>

    {% if comment.livechatresponse_set.exists %}
    <div class="head">
        {% for response in comment.livechatresponse_set.all %}
            <div class="t {% cycle 'even' 'odd' %}">
            <span>
                <strong>{{response.author.first_name}}</strong>
                -
                {{ response.updated_at|timesince }} ago
            </span><br/>
            <span>{{response.response}}</span>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    </div>
{% empty %}
You haven't asked any questions.
{% endfor %}
</div>
{% endif %}

<h2 id="comment_list">Questions</h2>
<p>
    <strong>Display: </strong>
    <a href="{{request.path}}">all questions</a>,
    <a href="?answered=true">questions with answers</a>,
    <a href="?answered=false">questions without answers</a> or
    <a href="?popular=true">most popular questions first</a>.
</p>
<div class="comment_list">
    {% for comment in page.object_list %}
    <div class="comment {% cycle 'even' 'odd' %}">
        <div class="head">
            <strong>
                {% if comment.user.get_profile.comment_as_anon %}
                    Anon.
                {% else %}
                    {% if comment.user.get_profile.fullname %}
                        <a href="{% url profile_view comment.user.pk %}">{{ comment.user.get_profile.fullname }}</a>
                    {% else %}
                        Anon.
                    {% endif %}
                {% endif %}
            </strong>
         -

        {{ comment.submit_date|date:"D, j M Y, H:i" }}

        <div>{% spaceless %}
            {% if comment.is_community_moderated %}
                <strong>Moderated:</strong> {{ comment.community_moderation_flags.latest.reason }}
            {% else %}
                {% if comment.is_moderated %}
                    <strong>Moderated:</strong> {{ comment.moderation_flags.latest.reason }}
                {% else %}
                    {{ comment.comment }}
                {% endif %}
            {% endif %}{% endspaceless %}
        </div>
        </div>

        <div class="base">
            <span class="likes">
                {{ comment.like_count }} Like{{ comment.like_count|pluralize }}
            </span>
            {% if user.is_authenticated %}
                <span class="tag"><a href="{% url comment_like comment.pk %}">+Like</a></span>
                <span class="tag report"><a href="{% url comment_flag comment.pk %}">Report</a></span>
                <span class="reports tag">
                    {% with flag_count=comment.community_moderation_flags.latest.flag_count %}
                    {% if flag_count %}{{ flag_count }}{% else%} 0 {%endif%}
                    {% endwith %}
                </span>
            {% else %}
                <span class="tag"><a href="{% url login %}?next={{request.path}}">+Like</a></span>
                <span class="tag report"><a href="{% url login %}?next={{request.path}}">Report</a></span>
                <span class="reports tag">
                    {% with flag_count=comment.community_moderation_flags.latest.flag_count %}
                    {% if flag_count %}{{ flag_count }}{% else%} 0 {%endif%}
                    {% endwith %}
                </span>
            {% endif %}
        </div>
        {% if comment.livechatresponse_set.exists %}
        <div class="head">
            {% for response in comment.livechatresponse_set.all %}
                <div class="t {% cycle 'even' 'odd' %}">
                <span>
                    <strong>{{response.author.first_name}}</strong>
                    -
                    {{ response.updated_at|date:"D, j M Y, H:i" }}
                </span><br/>
                <span>{{response.response}}</span>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        </div>
    {% endfor %}
</div>

<div id="pagination">
    {% if page.has_previous %}
        <span><a href="?p={{page.previous_page_number}}&amp;answered={{answered}}&amp;popular={{popular}}">Previous</a></span> |
    {% else %}
        <span>Previous</span> |
    {% endif %}

    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>

    {% if page.has_next %}
        | <span><a href="?p={{page.next_page_number}}&amp;answered={{answered}}&amp;popular={{popular}}">Next</a></span>
    {% else %}
        | <span>Next</span>
    {% endif %}
</div>